export const ActionTypes = {
    THEME_MODE: "THEME_MODE",
    NAV_COLOR: "NAV_COLOR",
    LOADER: "LOADER",
    MENU_COLLAPSE: "MENU_COLLAPSE",
    ACCESSED_MENU: "ACCESSED_MENU",
    ACCESSED_SUB_MENU: "ACCESSED_SUB_MENU",
    SHOW_ONLY_MENU_ICON: "SHOW_ONLY_MENU_ICON",
    SHOW_FULL_MENU: "SHOW_FULL_MENU",
    FEEDBACK: "FEEDBACK",
    AUTHORIZATION: "AUTHORIZATION",
    USER_PROFILE: "USER_PROFILE",
    USER_AUTHORIZED: "USER_AUTHORIZED",
    VALIDATE_SESSION: "VALIDATE_SESSION",
    LOGOUT:"LOGOUT",
    RESET_STORE:"RESET_STORE"
};
